project_id = "zugtdutimulibaxwnlbs"

[api]
port = 54321

[db]
port = 54322
major_version = 15

[auth]
enable_signup = true
additional_redirect_urls = ["http://localhost:8080", "http://localhost:5173", "http://127.0.0.1:5173", "http://127.0.0.1:8080"]

[auth.external.google]
enabled = true
client_id = "mock-google-client-id"
secret = "mock-google-secret"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[auth.external.apple]
enabled = true
client_id = "mock-apple-client-id"
secret = "mock-apple-secret"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[studio]
port = 54323

[functions.hello-world]
import_map = "./import_map.json"

[functions.health-check]
import_map = "./import_map.json"

[functions.rate-limit-check]
import_map = "./import_map.json"

[functions.process-background-jobs]
import_map = "./import_map.json"

[functions.realtime-chat]
import_map = "./import_map.json"

[functions.user-profiles]
import_map = "./import_map.json"

[functions.webrtc-signaling]
import_map = "./import_map.json"

[functions.discussion-room-create]
import_map = "./import_map.json"

[functions.discussion-room-get-messages]
import_map = "./import_map.json"

[functions.discussion-room-join-room]
import_map = "./import_map.json"

[functions.discussion-room-leave-room]
import_map = "./import_map.json"

[functions.discussion-room-list-rooms]
import_map = "./import_map.json"

[functions.discussion-room-update-room]
import_map = "./import_map.json"

[functions.send-notification]
import_map = "./import_map.json"

[functions.push-reply]
enabled = true
verify_jwt = true
import_map = "./functions/push-reply/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/push-reply/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/push-reply/*.html" ]
