// Cross-implementation E2EE round-trip test: web (apps/web/src/lib/e2ee/core.ts) <-> mobile (packages/e2ee/src/e2ee.ts).
// Run from the repo root:  npx tsx scripts/e2ee-interop-test.ts
(globalThis as any).window = globalThis;

import * as W from '../apps/web/src/lib/e2ee/core';
import * as M from '../packages/e2ee/src/e2ee';

let pass = 0;
let fail = 0;
const check = (name: string, ok: boolean, extra = '') => {
  if (ok) pass++; else fail++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${extra ? '  ' + extra : ''}`);
};

const samples = [
  'hello',
  'Unicode: नमस्ते 🎬 — “quotes” ñ',
  'x'.repeat(5000),
  '{"json":"looking","text":true}',
];

async function main() {
  // Keys generated by each implementation
  const wKp = await W.generateUserKeyPair();
  const mKp = await M.generateUserKeyPair();
  const wPub = await W.exportPublicKey(wKp.publicKey);
  const wPriv = await W.exportPrivateKey(wKp.privateKey);
  const mPub = await M.exportPublicKey(mKp.publicKey);
  const mPriv = await M.exportPrivateKey(mKp.privateKey);

  check('key formats identical (spki/pkcs8 base64 length class)', Math.abs(wPub.length - mPub.length) < 8 && Math.abs(wPriv.length - mPriv.length) < 200);

  for (const text of samples) {
    const tag = text.slice(0, 12).replace(/\n/g, ' ');
    // web sender -> mobile recipient
    const c1 = await W.encryptDirectMessage(text, wPub, mPub);
    check(`DM web->mobile (recipient decrypts) [${tag}]`, (await M.decryptDirectMessage(c1, mPriv, false)) === text);
    check(`DM web->mobile (sender copy via mobile impl) [${tag}]`, (await M.decryptDirectMessage(c1, wPriv, true)) === text);
    // mobile sender -> web recipient
    const c2 = await M.encryptDirectMessage(text, mPub, wPub);
    check(`DM mobile->web (recipient decrypts) [${tag}]`, (await W.decryptDirectMessage(c2, wPriv, false)) === text);
    check(`DM mobile->web (sender copy via web impl) [${tag}]`, (await W.decryptDirectMessage(c2, mPriv, true)) === text);
  }

  // Group (AES) messages
  const wGroup = await W.generateGroupKey();
  const gB64 = await W.exportSymmetricKey(wGroup);
  for (const text of samples) {
    const tag = text.slice(0, 12);
    const g1 = await W.encryptWithSymmetricKey(text, gB64);
    check(`Group AES web->mobile [${tag}]`, (await M.decryptWithSymmetricKey(g1, gB64)) === text);
    const g2 = await M.encryptWithSymmetricKey(text, gB64);
    check(`Group AES mobile->web [${tag}]`, (await W.decryptWithSymmetricKey(g2, gB64)) === text);
  }

  // Group key wrapping (RSA-OAEP of the AES key) across implementations
  const wrapped1 = await W.encryptWithPublicKey(gB64, mPub);
  check('Group key wrap web->mobile', (await M.decryptWithPrivateKey(wrapped1, mPriv)) === gB64);
  const wrapped2 = await M.encryptWithPublicKey(gB64, wPub);
  check('Group key wrap mobile->web', (await W.decryptWithPrivateKey(wrapped2, wPriv)) === gB64);

  // PIN backup (web-encrypted backup restored by mobile, and vice versa)
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const b1 = await W.encryptPrivateKeyWithPin(wPriv, '123456');
  const r1 = await M.decryptPrivateKeyWithPin(b1.encryptedKey, '123456', b1.salt);
  check('PIN backup web->mobile restore', r1 === wPriv);
  const b2 = await M.encryptPrivateKeyWithPin(mPriv, '654321');
  const r2 = await W.decryptPrivateKeyWithPin(b2.encryptedKey, '654321', b2.salt);
  check('PIN backup mobile->web restore', r2 === mPriv);
  let wrongPinRejected = false;
  try { await W.decryptPrivateKeyWithPin(b1.encryptedKey, '000000', b1.salt); } catch { wrongPinRejected = true; }
  check('Wrong PIN rejected', wrongPinRejected);
  void salt;

  console.log(`\n${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}

main().catch((e) => { console.error('HARNESS ERROR', e); process.exit(2); });
