-- project_architecture.sql

-- 1. Project Spaces & Categories
CREATE TABLE IF NOT EXISTS public.project_space_categories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text NOT NULL UNIQUE,
    description text
);

-- Create projects table (matches remote schema)
CREATE TABLE IF NOT EXISTS public.projects (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    title text NOT NULL,
    description text,
    creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text DEFAULT 'draft',
    start_date date,
    end_date date,
    location text,
    budget_min numeric,
    budget_max numeric,
    is_public boolean DEFAULT true,
    genre text[],
    required_roles text[],
    current_team jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    image_url text
);

CREATE TABLE IF NOT EXISTS public.project_spaces (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    description text,
    creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    category_id uuid REFERENCES public.project_space_categories(id) ON DELETE SET NULL,
    tags text[],
    last_activity_at timestamp with time zone DEFAULT now(),
    project_space_type public.project_space_type DEFAULT 'public'::project_space_type,
    status TEXT, 
    location TEXT, 
    genre TEXT[], 
    required_roles TEXT[],
    budget_min NUMERIC, 
    budget_max NUMERIC, 
    start_date DATE, 
    end_date DATE,
    project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE UNIQUE
);

CREATE TABLE IF NOT EXISTS public.project_space_members (
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'member',
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (project_space_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.project_space_join_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    message text,
    status text DEFAULT 'pending'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.project_space_bookmarks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, project_space_id)
);

-- 2. Project Management (Tasks, Files, Shotlists)
CREATE TABLE IF NOT EXISTS public.tasks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    due_date date,
    assignee_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    is_completed boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Functions (match remote schema)
CREATE OR REPLACE FUNCTION public.check_is_project_member(_project_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.project_space_members
    WHERE project_space_id = _project_id
    AND user_id = auth.uid()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.check_is_project_creator(_project_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.projects 
    WHERE id = _project_id 
    AND creator_id = auth.uid()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_member_of_project(_project_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.project_space_members 
    WHERE project_space_id = _project_id AND user_id = (select auth.uid())
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_project_member(_project_space_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.project_space_members 
    WHERE project_space_id = _project_space_id 
    AND user_id = auth.uid()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_project_creator(_project_space_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.project_spaces ps
    JOIN public.projects p ON ps.project_id = p.id
    WHERE ps.id = _project_space_id 
    AND p.creator_id = auth.uid()
  );
END;
$$;

-- Enable RLS
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Policies for projects
DROP POLICY IF EXISTS "Create Projects" ON public.projects;
CREATE POLICY "Create Projects" ON public.projects FOR INSERT WITH CHECK (auth.role() = 'authenticated'::text);

DROP POLICY IF EXISTS "View Projects" ON public.projects;
CREATE POLICY "View Projects" ON public.projects FOR SELECT USING ((is_public = true) OR (creator_id = auth.uid()) OR check_is_project_member(id));

DROP POLICY IF EXISTS "Manage Projects" ON public.projects;
CREATE POLICY "Manage Projects" ON public.projects FOR ALL USING (creator_id = auth.uid());

-- Policies for project_spaces
DROP POLICY IF EXISTS "Create Project Spaces" ON public.project_spaces;
CREATE POLICY "Create Project Spaces" ON public.project_spaces FOR INSERT WITH CHECK (auth.role() = 'authenticated'::text);

DROP POLICY IF EXISTS "Manage Project Spaces" ON public.project_spaces;
CREATE POLICY "Manage Project Spaces" ON public.project_spaces FOR ALL USING (check_is_project_creator(project_id));

DROP POLICY IF EXISTS "View Project Spaces" ON public.project_spaces;
CREATE POLICY "View Project Spaces" ON public.project_spaces FOR SELECT USING (((((project_space_type)::text = ANY (ARRAY['public'::text, 'private'::text])) AND (auth.role() = 'authenticated'::text)) OR (((project_space_type)::text = 'secret'::text) AND (is_project_member(id) OR check_is_project_creator(project_id))) OR is_project_member(id) OR check_is_project_creator(project_id)));

DROP POLICY IF EXISTS "Auth View Projects" ON public.project_spaces;
CREATE POLICY "Auth View Projects" ON public.project_spaces FOR SELECT USING (((( SELECT auth.role() AS role) = 'authenticated'::text) AND ((project_space_type = 'public'::project_space_type) OR (creator_id = ( SELECT auth.uid() AS uid)) OR is_member_of_project(id))));

DROP POLICY IF EXISTS "Auth Create Projects" ON public.project_spaces;
CREATE POLICY "Auth Create Projects" ON public.project_spaces FOR INSERT WITH CHECK ((( SELECT auth.role() AS role) = 'authenticated'::text));

DROP POLICY IF EXISTS "Creator Manage Projects" ON public.project_spaces;
CREATE POLICY "Creator Manage Projects" ON public.project_spaces FOR ALL USING ((( SELECT auth.uid() AS uid) = creator_id));

-- Policies for tasks
DROP POLICY IF EXISTS "Members can view tasks" ON public.tasks;
CREATE POLICY "Members can view tasks" ON public.tasks FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.project_space_members WHERE project_space_id = tasks.project_space_id AND user_id = auth.uid())
);

-- 3. Project Applications
CREATE TABLE IF NOT EXISTS public.project_applications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    cover_letter text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(project_id, user_id)
);

ALTER TABLE public.project_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "View Own Applications" ON public.project_applications;
CREATE POLICY "View Own Applications" ON public.project_applications
FOR SELECT USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Creator View Applications" ON public.project_applications;
CREATE POLICY "Creator View Applications" ON public.project_applications
FOR SELECT USING (
  EXISTS (
      SELECT 1 FROM public.projects WHERE id = project_applications.project_id AND creator_id = auth.uid()
  )
  OR 
  EXISTS (
      SELECT 1 FROM public.project_spaces ps 
      JOIN public.projects p ON ps.project_id = p.id 
      WHERE ps.id = project_applications.project_id AND p.creator_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Manage Applications" ON public.project_applications;
CREATE POLICY "Manage Applications" ON public.project_applications
FOR ALL USING (user_id = auth.uid());

DROP TRIGGER IF EXISTS update_project_applications_updated_at ON public.project_applications;
CREATE TRIGGER update_project_applications_updated_at
BEFORE UPDATE ON public.project_applications
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

