-- project_architecture.sql

-- 1. Project Spaces & Categories
CREATE TABLE IF NOT EXISTS public.project_space_categories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name text NOT NULL UNIQUE,
    description text
);

CREATE TABLE IF NOT EXISTS public.project_spaces (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    description text,
    creator_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    category_id uuid REFERENCES public.project_space_categories(id) ON DELETE SET NULL,
    tags text[],
    last_activity_at timestamp with time zone DEFAULT now(),
    project_space_type public.project_space_type DEFAULT 'public'::project_space_type,
    status TEXT, 
    location TEXT, 
    genre TEXT[], 
    required_roles TEXT[],
    budget_min NUMERIC, 
    budget_max NUMERIC, 
    start_date DATE, 
    end_date DATE,
    cover_image text
);

CREATE TABLE IF NOT EXISTS public.project_space_members (
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'member',
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (project_space_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.project_space_join_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    message text,
    status text DEFAULT 'pending'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.project_space_bookmarks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(user_id, project_space_id)
);

-- 2. Project Management (Tasks, Files, Shotlists)
CREATE TABLE IF NOT EXISTS public.tasks (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_space_id uuid NOT NULL REFERENCES public.project_spaces(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    due_date date,
    assignee_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    is_completed boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.project_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_space_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Policies (Simplified for development)
CREATE POLICY "Anyone can view project spaces" ON public.project_spaces FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create project spaces" ON public.project_spaces FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Creators can manage their projects" ON public.project_spaces FOR ALL USING (auth.uid() = creator_id);
CREATE POLICY "Members can view tasks" ON public.tasks FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.project_space_members WHERE project_space_id = tasks.project_space_id AND user_id = auth.uid())
);
